spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/shopora_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Mahi@7781
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    # Redis Configuration Setup
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password:        # Leave blank if your local Redis instance does not have a password
#      timeout: 60000ms # Connection timeout configuration

# JWT Configuration
jwt:
  secret: ThisIsAVeryLongSecretKeyForJwtTokenGenerationMustBeAtLeast256BitsLong1234567890
  admin-expiration-ms: 900000